const moviesList = [
    {
      id:1,
      name: "Avengers: Endgame",
      releaseDate: "April 26, 2019",
      image: "https://image.tmdb.org/t/p/original/yaRps1bMQLyz54M8ib5YdA2a2RZ.jpg",
      clipID:"TcMBFSGVi1c",
      summary: "The Avengers unite to reverse the destruction caused by Thanos and restore order to the universe.",
      length: "3 hours 2 minutes",
      cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    },
    {id:2,
      name: "Mission: Impossible - Rogue Nation",
      clipID:"pXwaKB7YOjw",
      releaseDate: "July 31, 2015",
      image: "https://blogs-images.forbes.com/scottmendelson/files/2015/07/Mission-Impossible-Rogue-Nation-2015-Poster-HD-wallpaper.jpg",
      summary: "Ethan Hunt and his team uncover a global terrorist network called the Syndicate and try to bring them down.",
      length: "2 hours 11 minutes",
      cast: ["Tom Cruise", "Jeremy Renner", "Simon Pegg", "Rebecca Ferguson", "Ving Rhames"],
    },
    {id:3,
      name: "One Piece Red",
      clipID:"89JWRYEIG-s",
      releaseDate: "TBA",
      image: "https://i.ytimg.com/vi/IjjYPBQ0UzQ/maxresdefault.jpg",
      summary: "Monkey D. Luffy and his crew continue their adventures as they search for the ultimate treasure, the One Piece.",
      length: "TBA",
      cast: ["Mayumi Tanaka", "Kazuya Nakai", "Akemi Okamura", "Kappei Yamaguchi", "Hiroaki Hirata"],
    },
    {id:4,
      name: "Harry Potter and the Philosopher's Stone",
      clipID:"mNgwNXKBEW0",
      releaseDate: "November 16, 2001",
      image: "https://wallpapercave.com/wp/wp6289310.jpg",
      summary: "Harry Potter discovers he is a wizard and begins his magical education at Hogwarts School of Witchcraft and Wizardry.",
      length: "2 hours 32 minutes",
      cast: ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Richard Harris", "Maggie Smith"],
    },
    {id:5,
      name: "Oppenheimer",
      clipID:"uYPbbksJxIg",
      releaseDate: "July 21 2023",
      image: "https://images.mid-day.com/images/images/2022/jul/openheimer_d.jpg",
      summary: "A biographical drama about J. Robert Oppenheimer, the physicist who led the development of the atomic bomb.",
      length: "2 hours and 49 minutes",
      cast: ["Cillian Murphy","Emily Blunt","Matt Damon"],
    },
    {id:6,
      name: "Transformers",
      clipID:"fnXzKwUgDhg",
      releaseDate: "July 3, 2007",
      image: "https://wallpapercave.com/wp/wp3191920.jpg",
      summary: "The battle between the Autobots and the Decepticons, two alien robot factions, comes to Earth.",
      length: "2 hours 23 minutes",
      cast: ["Shia LaBeouf", "Megan Fox", "Josh Duhamel", "Tyrese Gibson", "John Turturro"],
    },
    {id:7,
      name: "Venom",
      releaseDate: "October 5, 2018",
      clipID:"u9Mv98Gr5pY",
      image: "https://i.pinimg.com/originals/b4/a6/18/b4a6188690111e8c36ad8bbf2fd70720.jpg",
      summary: "Journalist Eddie Brock gains superhuman abilities after becoming the host of an alien symbiote known as Venom.",
      length: "1 hour 52 minutes",
      cast: ["Tom Hardy", "Michelle Williams", "Riz Ahmed", "Scott Haze", "Reid Scott"],
    },
    {id:8,
      name: "Pirates of the Caribbean",
      clipID:"naQr0uTrH_s",
      releaseDate: "July 9, 2003",
      image: "https://www.wallpaperflare.com/static/88/898/574/pirates-of-the-caribbean-pirates-of-the-caribbean-on-stranger-tides-jack-sparrow-johnny-depp-wallpaper.jpg",
      summary: "Captain Jack Sparrow teams up with a blacksmith and a governor's daughter to save his stolen ship and rescue his love from cursed pirates.",
      length: "2 hours 23 minutes",
      cast: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Geoffrey Rush", "Jonathan Pryce"],
    },
    {id:9,
      name: "Cars 3",
      clipID:"https://youtu.be/2LeOH9AGJQM",
      releaseDate: "June 16, 2017",
      image: "https://cdn.images.express.co.uk/img/dynamic/36/590x/secondary/cars3-813877.jpg",
      summary: "Lightning McQueen, now facing a new generation of fast racers, seeks help from a young race technician to make a comeback in the racing world.",
      length: "1 hour 42 minutes",
      cast: ["Owen Wilson", "Cristela Alonzo", "Chris Cooper", "Nathan Fillion", "Larry the Cable Guy"],
    }
  ];
  export default moviesList;